# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_logging', '0004_auto_20171124_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='uuid',
            field=models.UUIDField(help_text='used to mark multiple actions of the same origin', null=True),
        ),
    ]
